### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#102]
Current one: https://www.lacounts.org/contact/

![contact - desktop](https://user-images.githubusercontent.com/200230/46728039-2e55f480-cc82-11e8-86f9-c05971af965a.jpg)

Route + Controller that renders template with form + When submitting send an email to hello@lacounts.org

**Comment by brew** [comment]
This is added by 6f23f4c95cfdbbf7e8d5af6e1180af0a7d9cb5e7, but as we currently use Mandrill to send email, we will need the lacounts.org sending domain verified (https://mandrill.zendesk.com/hc/en-us/articles/205582267-About-SPF-and-DKIM#set-up-spf-and-dkim-for-your-sending-domains).
