### ISSUE TITLE
About should not be highlighted in the header

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#103]
It should be a call to action like Get Involved or something

![screenshot_2018-10-11 organizations - la counts](https://user-images.githubusercontent.com/200230/46799068-12228800-cd54-11e8-97e2-6a9bd18a7dd2.png)

**Comment by smth** [comment]
Fixed in https://github.com/okfn/ckanext-lacounts/commit/61795263274ecd604d922a7df9551bb3e5a90130.
