### ISSUE TITLE
Enable tracking (Trending datasets)

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#131]
This involves adding the plugin and the background job that crushes the numbers.
In terms of the UI, the little fire icon should be displayed in the dataset page (#111) and search results

**Comment by roll** [comment]
@amercader 
Is `ckanext-googleanalytics` not enough?

**Comment by amercader** [comment]
@roll IIRC correctly the "trending" thing came from an internal tracking CKAN feature. If ckanext-googleanalytics provides it great though. I'll double check.

**Comment by roll** [comment]
@amercader 
> CKAN extension to integrate Google Analytics data into CKAN. Gives download stats on package pages, list of most popular packages, etc.

**Comment by roll** [comment]
Also, run in the `package_item` snippet:

```
 {{ h.popular('recent views', package.tracking_summary.recent, min=10) if package.tracking_summary }}
```

**Comment by roll** [comment]
@amercader 
I will start this one tomorrow morning if you don't mind. As I have nothing more to do until I sync with Sam or you

**Comment by roll** [comment]
So `ckanext-googleanalytics` doesn't seem support trending for ckan@2. So we have to follow this instruction - https://docs.ckan.org/en/2.8/maintaining/tracking.html

**Comment by roll** [comment]
DONE
