### ISSUE TITLE
Search doesn't work on the dataset page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#142]
eg https://lacounts-staging.l3.ckan.io/dataset/fire-hydrants

Searching for something redirects to a wrong URL:

https://lacounts-staging.l3.ckan.io/dataset/dataset?q=fire

**Comment by roll** [comment]
That's weird that it's back

**Comment by roll** [comment]
That's weird - https://github.com/okfn/ckanext-lacounts/commit/05b676f0848ae79ea9e14edf7cb7d9a3ce0e3ab2

I will re-fix

**Comment by roll** [comment]
FIXED
