### ISSUE TITLE
Remove images from publishers

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#146]
From the publishers schema, and also from the publisher pages:

![screenshot_2018-11-07 southern california association of governments - publishers - la counts](https://user-images.githubusercontent.com/200230/48129123-e0380f00-e288-11e8-8091-d609c7a9ff35.png)

Also remove the list below the image with the title, which comes from the hierarchy extension

**Comment by roll** [comment]
DONE
