### ISSUE TITLE
Methodology and About the Author sections on Story page

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#147]
# Overview

Methodology is a new optional field, which is a link to a another story (of type methodology). 

On About the author there can be two things:

* A link to a story (of type author profile). If it is present, we display the title of the story, which is a link to it.
* If there is no author profile story linked, we displayed the static details that we are showing now.

@roll add any extra new fields needed for this.

# Tasks

- [x] implement `methodology`
- [x] implement `about the author`

**Comment by roll** [comment]
Author - https://lacounts-staging.l3.ckan.io/story/wage-by-race-ethnicity-in-common-jobs

**Comment by roll** [comment]
DONE
