### ISSUE TITLE
Create additional topics

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#156]
There's an existing command line script for creating topics in [here](https://github.com/okfn/ckanext-lacounts/blob/master/ckanext/lacounts/commands.py). Please expand it to add the following topics if not already present:

topic | featured
-- | --
administrative boundaries |  
arts + culture |  
census |  
community + economic development |  
demographics |  
education | x
environment | x
equity |  
food |  
government services |  
government spending |  
health + wellbeing | x
housing | x
immigration | x
infrastructure |  
LA Counts |  
natural disasters |  
philanthropy |  
recreation |  
safety |  
schools |  
transportation | x
water |  

Ideally I'd like to move this script to a standalone Python one likes the one located in the `scripts/` folder, as this allows us to run it directly from a dev machine on any site (assuming we have an API key)

**Comment by roll** [comment]
DONE
