### ISSUE TITLE
Search is returning different results with the same search parameter

### ISSUE THREAD

**Issue by carlacasilli** [okfn/ckanext-lacounts#187]
Searched for "economy panel" on the production site and it returned no results. Wrote "economypanel" and it returned 1 result and then wrote "economy panel" again and it returned 4 results.

**Comment by amercader** [comment]
I get consistent results with the following terms:

* [economy panel](https://lacounts.ckan.io/dataset?q=economy%20panel) (unquoted) : 4 results
* ["economy panel"](https://lacounts.ckan.io/dataset?q="economy%20panel") (quoted): 1 result
* [economy panel](https://lacounts.ckan.io/dataset?q=economypanel): 1 result

Not sure why you didn't get results in the first instance, but we'll keep an eye in case it happens again.

**Comment by carlacasilli** [comment]
To be clear, the searches did not include quotes they were a mix of spaces and no spaces:

- economy panel
- economypanel
- economy panel

and each of these queries returned different results. Emily was seated next to me when this happened.

Also, can you explain why the first and third of *your* bullet points return two different results? They appear to be the same thing.

**Comment by amercader** [comment]
If any of these queries returned no results then is definitely a bug and we need to investigate it. If you notice it again copy the full URL and add it to this issue so we can replicate it, and the time when it happened in case is something related to a background job.

The results I listed in my previous comment are expected. `economy panel` will return all datasets with these two terms in any of the indexed metadata fields (all fields are indexed), so these 4 datasets have both terms in some field (eg harvest source title, or the topic they belong to). `"economy panel"` will return results where the two words are found together (eg [this dataset](https://lacounts.ckan.io/dataset/economy-panel-la-data)). `economypanel` will return datasets where this single word is found (ie the [same dataset as before](https://lacounts.ckan.io/dataset/economy-panel-la-data)).


> Also, can you explain why the first and third of your bullet points return two different results? They appear to be the same thing.

Sorry that was badly formatted, the third item does not contain spaces

**Comment by jobarratt** [comment]
closing. @carlacasilli please reopen if still relevant
