### ISSUE TITLE
search bar inconsistencies

### ISSUE THREAD

**Issue by emillipede** [okfn/ckanext-lacounts#205]
for example, if I try to initiate a search from the header search bar when this page, https://www.lacounts.org/publisher/county-of-los-angeles, or this page, https://www.lacounts.org/topic, I get no search results https://www.lacounts.org/dataset?q=earthquake&sort=None

but if I attempt this search from the library page, I get 18 results https://www.lacounts.org/dataset?q=earthquake&sort=score+desc%2C+metadata_modified+desc

**Comment by amercader** [comment]
Thanks @emillipede, the problem is the `&sort=None` bit that gets added. We'll investigate and remove it

**Comment by emillipede** [comment]
I think this bug may relate to another I've just noticed - when I am searching through content on the library page and enter a new term into the search bar, the filters don't clear. eg, if I search for "hospital" and then filter to only display data from the publisher "los angeles, county of" and then initiate a new search (eg. "mountain"), I'll get a "no results" response and shows that the search was done with the publisher filter still active. 

As I understand it, the expected outcome of a new search is one with no filters in place.
