### ISSUE TITLE
Redirect "/catalog/####" to /dataset (Library page)

### ISSUE THREAD

**Issue by joshuazrobins** [okfn/ckanext-lacounts#214]
Can we setup a redirect for users who try to access a dataset using an "old" link (in the style of our previous URL formatting)? 

For example, we previously formatted our URL like "www.lacounts.org/catalog/4447" for a dataset. What we are finding is there are users who saved old URL shortcuts and attempt to access these dataset pages now. The result is a 404 ERROR. 

Instead of this 404 ERROR, can we redirect these users accessing any "/catalog/___" URL to the standard Library page "/dataset" ?

**Comment by emillipede** [comment]
It’d be great to also redirect from URLs built like https://lacounts.org to
functional URLs https://www.lacounts.org

**Comment by roll** [comment]
DONE
