### ISSUE TITLE
Resource's embed button doesn't work

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#22]
# Overview

Clicking on the `Embed` button (ckan2.8) leads to an empty modal.

![embed](https://user-images.githubusercontent.com/557395/44020480-bfcbb58c-9eea-11e8-8f67-c1aee199c131.png)

**Comment by roll** [comment]
cc @amercader 
Not sure what is it. I don't see any plugins involved - can it be a ckan bug?

**Comment by amercader** [comment]
mmm works on a plain 2.8 instance
https://beta.ckan.org/dataset/beta-dataset-200/resource/b2b49b02-d2d3-4e77-a2b6-cc85d93ccf10

is there anything in the console?

**Comment by roll** [comment]
@amercader
I'll check thanks. Did not know about this Beta demo to verify
