### ISSUE TITLE
Stories schema

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#25]
We need to clarify what fields are needed to collect and display when creating a story.
Fields mentioned so far include Methodology, but it's still unclear if that is need.

Also stories need to be able to be added to Groups (Areas of Interest / Categories)

**Comment by amercader** [comment]
This is now ready to be implemented using the fields on the spreadsheet above.

**Comment by amercader** [comment]
Showcases does not use scheming so fields are currently defined using the `IDatasetForm` [methods](https://github.com/okfn/ckanext-showcase/blob/master/ckanext/showcase/plugin.py#L85:L92)

**Comment by roll** [comment]
> Also stories need to be able to be added to Groups (Areas of Interest / Categories)
Moved to a separate issue (#34)
