### ISSUE TITLE
Display stories alongside dataset search results

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#28]
There is a [config option](http://docs.ckan.org/en/2.8/maintaining/configuration.html#ckan-search-show-all-types) that is meant to control what dataset types (ie `dataset` and/or `showcase`) are queried in order to display the search results. But it doesn't look like [the implementation](https://github.com/ckan/ckan/blob/master/ckan/controllers/package.py#L229:L251) allows two simultaneous dataset types (eg `ckan.search.show_all_types = dataset showcase`).

Of course it's worth giving it a try but if it doesn't work I think our best option is to implement the `before_search` method of the `IPackageController` interface and handle the `fq` parameter ourselves.

**Comment by roll** [comment]
I've just had a case for `fq` usage:
https://github.com/okfn/ckanext-showcase/blob/14a554310c9403278be599805ce84aeec900b937/ckanext/showcase/controller.py#L205-L208

**Comment by roll** [comment]
It's weird but I don't see any difference with (looking into solr queries):
```
http://docs.ckan.org/en/2.8/maintaining/configuration.html#ckan-search-show-all-types = True
http://docs.ckan.org/en/2.8/maintaining/configuration.html#ckan-search-show-all-types = False
```

I used different approach anyway but curious...
