### ISSUE TITLE
Ability adding to a story one or more topics

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#34]
# Overview

For datasets it works like this:

![topics](https://user-images.githubusercontent.com/557395/44506778-9a6ba180-a6b0-11e8-8e1e-1b574df79ce1.png)

We need the same for stories.

**Comment by amercader** [comment]
@roll is stored on the `member` table

**Comment by roll** [comment]
Ahh thanks, I see now. Had looked into this table but missed a test association.
