### ISSUE TITLE
Base CKAN installs with default extensions

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#4]
This should be applied to the [development environment](https://github.com/okfn/docker-ckan-lacounts) and to the staging site.

Extensions:
- [x] Harvest
- [x] DataStore
- [x] GeoView
  - [x] ~~geo_view~~ -> #11 
  - [x] geojson_view
- [x] PDFView
- [x] GoogleAnalytics
- [x] Disqus (commenting)

Park for now:
- Spatial
- Showcase/pages

All of them need to have a quick review to see if they work on CKAN 2.8

**Comment by amercader** [comment]
To test the extensions are working fine:

- [ ] Harvest: Add the `harvest ckan_harvester` plugins. Create a CKAM harvest source in `/harvest/new`. After a few minutes there should be some harvesting output in the logs (maybe not depending on the setup?) and datasets should start to be created.
- [ ] DataStore: This should work fine. Add the `datapusher datastore` plugins and upload a CSV file. You should get the green Data API button on the resource page
- [ ] GeoView: Add the `geo_view and geojson_view` plugins, and the following config options: `CKANEXT__GEOVIEW__OL_VIEWER__FORMATS=wms wfs gml kml` and `CKAN__VIEWS__DEFAULT_VIEWS=image_view text_view recline_view geo_view pdf_view geojson_view`. Then upload a GeoJSON file and a WMS service URL (like this one). In both cases a map should appear.
- [ ] PDFView: Add the `pdf_view` plugin and upload a PDF, you should see a pdf viewer
- [ ] GoogleAnalytics: Add the `googleanalytics` plugin and the `CKAN___GOOGLEANALYTICS__ID=UA-XX-XX` option (with random values) and for now just check if the GA code is added to the source on the pages
- [ ] Disqus (commenting): Add the `disqus` plugin and the `CKAN___DISQUS__NAME=xxx` option. You can create a test account for now. The Disqus widget should appear in the dataset page.

**Comment by roll** [comment]
Notes:
