### ISSUE TITLE
Normalize harvested dataset fields into our own schema

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#40]
Harvested metadata will obviously have a different schema than the LA Counts site one. We need a way to match fields in the remote metadata to the ones expected in our site.

For instance, in this [CKAN dataset](https://data.chhs.ca.gov/api/action/package_show?id=park-beach-open-space-or-coastline-access&use_default_schema=True) from this [site](https://data.chhs.ca.gov), our `spatial_text` is called `geo_coverage` ([dataset page](https://data.chhs.ca.gov/dataset/park-beach-open-space-or-coastline-access)).

Or in this [Socrata dataset](http://api.us.socrata.com/api/catalog/v1?ids=r8vi-rxcc) from this [site](https://data.smgov.net), the value for `response['results']['classification']['domain_metadata']['key'] == 'Data-Freshness_Time-Period'` might be our `temporal_extent_start` / `temporal_extent_end` fields (need to check this).

Simple cases like the first one can probably be automated with a dictionary list of synonyms. More complex ones like the second one might need to be coded specifically.

In the automated case, and for CKAN instances we should look both at the root level and on the `extras` for the same potential key.

**Comment by roll** [comment]
@amercader 
After #49 we can start working on this. This issue is pretty ad-hoc, we need to go thru sources source by source. So probably we need to create a priority list first bases on the Google Doc. Also, we have to take into account that for now, we only have `CKANHarvester` implemented so `ckan` should should go first.

**Comment by roll** [comment]
Split:
- #51 
- #52 
- #53
