### ISSUE TITLE
Rename "Datasets" to "Library"

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#42]
![screenshot_2018-08-24 datasets - la counts 1](https://user-images.githubusercontent.com/200230/44582124-cbc39a80-a7a0-11e8-811d-342b70fcd5c8.png)

In the header menu and the breadcrums. The breadcrumbs might be a pain to override on all templates so perhaps we can get away with changing the translated string for "Datasets" to "Library" (but only this one)

**Comment by brew** [comment]
Closed by https://github.com/okfn/ckanext-lacounts/commit/57510738477616268912823e82fbff5055d63865.
