### ISSUE TITLE
Publishers page not listing items

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#48]
![screenshot_2018-08-28 publishers - la counts](https://user-images.githubusercontent.com/200230/44714340-5e23b100-aab5-11e8-8b42-3bd30b9e17db.png)

**Comment by brew** [comment]
Closed by https://github.com/okfn/ckanext-lacounts/commit/14662bcfe91397bc4b3c12c4f28bbcc233927cf3
