### ISSUE TITLE
Fix buttons and forms styling

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#72]
Action buttons look misaligned:
![screenshot_2018-09-20 u s census blocks in scag - la counts](https://user-images.githubusercontent.com/200230/46012374-53b30200-c0c9-11e8-95e5-1c776b229a9e.png)

and with the wrong font colour:
![screenshot_2018-09-20 library - la counts](https://user-images.githubusercontent.com/200230/46012388-5a417980-c0c9-11e8-8989-25c8ef21f3ac.png)

Also in general forms need a good review, as there is no consistency in the font size or also in the controls size:

![screenshot_2018-09-18 create dataset - la counts](https://user-images.githubusercontent.com/200230/45817369-dc532c00-bcde-11e8-9615-e241b6305523.png)

![screenshot_2018-09-18 create harvest source - la counts](https://user-images.githubusercontent.com/200230/45817368-dbba9580-bcde-11e8-9c56-3ede5bb42f64.png)

**Comment by amercader** [comment]
@roll The buttons are probably on @smth radar already, but given your experience with Bootstrap 3 on other extensions do you think you can fix the forms?

**Comment by roll** [comment]
@amercader 
I'll sync with Sam to understand what I can do

**Comment by roll** [comment]
I've removed myself from this, for now. It seems like there is a lot of coming work of different pages implementations. And Sam still should be much better at working with CSS.

Let's sync on it on the next planning.

**Comment by smth** [comment]
I think this should be more or less sorted with https://github.com/okfn/ckanext-lacounts/compare/user Let me know if not.
