### ISSUE TITLE
Add config option for showcased picture in the frontpage

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#77]
Copy the logic for uploading the logo image in the admin section, and add a config option for uploading the featured image.

@smth can you advise on what size should be recommend?

**Comment by smth** [comment]
At the moment I'm going to say 1100x600px.

**Comment by roll** [comment]
@amercader 
Do I understand correctly that we also need to implement logic like this somewhere (e.g. in some validator) to upload featured images:
```
    upload = uploader.get_uploader('admin')
    upload.update_data_dict(data_dict, 'ckan.site_logo',
                            'logo_upload', 'clear_logo_upload')
    upload.upload(uploader.get_max_image_size())
    data, errors = _validate(data_dict, schema, context)
    if errors:
        model.Session.rollback()
        raise ValidationError(errors)
```
It's a code from `ckan.logic.action.update:config_option_update`. And it doesn't seem supporting uploading other thinkgs except for `site_logo`.

**Comment by amercader** [comment]
@roll The only way I can think of is to override the core `config_option_update` action in our plugin, handle the image upload first, and then call the core one. I haven't tested though:

```python

def custom_config_option_update(context, data_dict):
    upload = uploader.get_uploader('admin')
    # This should update data_dict in place with the relevant field
    upload.update_data_dict(data_dict, 'ckan.homepage_featured_image',
                            'homepage_featured_image_upload', 'clear_homepage_featured_image_upload')
    upload.upload(uploader.get_max_image_size())
     
    return core_config_option_update(context, data_dict)

```

**Comment by roll** [comment]
@amercader 
Thanks for confirmation, already on it
