### ISSUE TITLE
Harvesting doesn't trigger re-build for the `Type` facet

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#78]
# Overview

It uses the `before_index` hook and works OK for dataset/story creation and updating. But it doesn't work for harvesting.

![facets](https://user-images.githubusercontent.com/557395/46013391-d4c3c680-c0d4-11e8-8aef-309516a4aafd.png)

**Comment by amercader** [comment]
Looks like this is working as expected now

![screenshot_2018-10-10 library - la counts](https://user-images.githubusercontent.com/200230/46732331-775f7600-cc8d-11e8-8965-a1fe3af2165e.png)
