### ISSUE TITLE
Jobs on staging are not finishing

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#86]
# Overview

Steps to reproduce:
- update any topic like `Housing`
- check on the logs: `2018-10-03T07:57:30+00:00 lacounts-staging[cmd.v77.gw4vp]: INFO:ckan.lib.jobs:Added background job f2cc321d-0606-4292-aba1-a7671b321806 to queue "default"`

But then there is neither any indication of job finishing nor any error messages.

**Comment by roll** [comment]
@amercader 
could you please take a look

**Comment by amercader** [comment]
Done. We were missing the `paster worker` command supervisor config.
The auto-tagging is now working

**Comment by amercader** [comment]
Spoke too soon

**Comment by amercader** [comment]
Working
