### ISSUE TITLE
Development: templates are not auto-reloaded and errors are hidden

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#95]
# Overview

There are a few problems with template developments:
- not auto-reloading on changes
- template errors don't appear in the logs

@smth 
@amercader
Just wrote down the issue we have discussed

**Comment by roll** [comment]
@amercader 
I'm not sure what's happened but I've started to get template error in the logs + now auto-reloading works again.

**Comment by roll** [comment]
No, it's back to worse state again. 

Also, I have found - https://docs.ckan.org/en/ckan-2.7.3/theming/templates.html#debug-footer

**Comment by amercader** [comment]
Fixed in the upstream image, pull the latest version to get it solved: https://github.com/okfn/docker-ckan-lacounts#updating-upstream-ckan-images
