### ISSUE TITLE
Wrong line breaks

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#99]
These look like something clearly wrong:

![screenshot_2018-10-10 city of santa monica employee trips with alternate transportation - la counts](https://user-images.githubusercontent.com/200230/46724145-b683cc00-cc79-11e8-9b98-620ef19d530e.png)

These are harder to replicate, Advocacy was on a new line in the homepage. I had to shrink the width quite a lot to replicate but the client reported it on a desktop screen. Could it be something font related? (ie the expected font didn't load)

![screenshot_2018-10-10 welcome - la counts](https://user-images.githubusercontent.com/200230/46724146-b683cc00-cc79-11e8-815a-d45b7b7da8c7.png)

**Comment by smth** [comment]
I'm not sure I understand this issue. In terms of the home page, is / was something definitely broken, or could it be that having the lines break at some points is undesirable? For example the above screenshot might be undesirable, but it is completely normal behaviour (that's not to say that the normal behaviour can't be changed).
